# Generated by Django 3.2.8 on 2022-08-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='scv_link',
            field=models.CharField(blank=True, max_length=256, verbose_name='Ссылка на репозиотрий'),
        ),
    ]
